---
name: Lint YAML.

on: [push]

jobs:
  lint-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Lint YAML files.
        uses: frenck/action-yamllint@v1
